name: MoreMinecartStarter
main: com.roboticoverlord.micro.bukkit.MinecartStarter
version: 1.3.1
commands:
    minecart:
        description: Spawns a minecart, places player in, and gives it initial momentum.
        usage: /<command>
permissions:
    micro.minecartstarter.can:
        description: Whether a player can use the /minecart command.
        default: true

